---
title: "Data Viz"
output: github_document
date: "2025-09-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(p8105.datasets)
data("weather_df")
library(patchwork)

```
## Scatterplot 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
    x = "Minimum Daily Temp",
    y = "maximum daily temp", 
    title = "temperature scatter plot",
    caption = "data from NOAA",
    color = "location"
  )
```

## Scales 
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
    x = "Minimum Daily Temp",
    y = "maximum daily temp", 
    title = "temperature scatter plot",
    caption = "data from NOAA",
    color = "location"
  ) +
  scale_x_continuous(
    breaks = c(-20, 0, 25), 
    labels = c("-20C", "0", "25"),
  ) +
  scale_y_continuous(
    trans = "sqrt",
    limits = c(10, 30)
  )
```

```{r}
ggp_temperature =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.5) +
  labs(
    x = "Minimum Daily Temp",
    y = "maximum daily temp", 
    title = "temperature scatter plot",
    caption = "data from NOAA",
    color = "location"
  ) +
  scale_x_continuous(
    breaks = c(-20, 0, 25), 
    labels = c("-20C", "0", "25"),
  ) +
  viridis::scale_color_viridis(
    discrete = TRUE
  )
```



## Themes 
make my base plot 

```{r}
ggp_temperature +
  theme_minimal() +
  theme(legend.position = "bottom")

```
```{r}
ggp_temperature +
  theme_bw () +
  theme(legend.position = "bottom")

ggsave("weather_scatterplot.png", ggp_temperature)
```
## Adding data to geoms 
```{r}
central_park_df = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

molokai_df = 
  weather_df %>% 
  filter(name == "Molokai_HI")

ggplot(data = molokai_df, aes(x = date, y = tmax, color = name))+
  geom_point() +
  geom_line(data = central_park_df)


```

## Patchwork
Make 3 polots and combine using patchwork 

```{r}
ggp_tmax_tmin = 
  weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name))+
  geom_point(alpha = 0.5)
  theme(legend.position = "none")

ggp_prec_density =
  weather_df %>% 
  filter(prcp > 0 ) %>% 
  ggplot(aes(x=prcp, fill = name))+
  geom_density(alpha = 0.5)

ggp_temp_season = 
   weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name))+
  geom_point(alpha = 0.5)
geom_smooth(se = FALSE)
 theme(legend.position = "bottom")

(ggp_tmax_tmin + ggp_prec_density) / ggp_temp_season

```
## data manipulation 

```{r}
weather_df %>% 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA")))
  ggplot(aes( x = name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.5)
```


```{r}
weather_df %>% 
  mutate(name = fct_reorder(name, tmax)) %>% 
  ggplot(aes( x = name, y = tmax, fill = name)) +
  geom_violin(alpha = 0.5)
```
Data tidyness
```{r}
pulse_df = 
  haven::read_sas("Data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
pivot_longer(
  bdi_score_bl:bdi_score_12m,
  names_to = "visit",
  values_to = "bdi"
) %>% 
  mutate(visit = fct_inorder(visit))

pulse_df %>% 
  ggplot(aes(x = visit, y = bdi))+
  geom_boxplot()
  
```

Make plot for FAS study 

```{r}
 read_csv("Data/FAS_pups.csv", na = c("NA", ".", ""), skip = 3) %>%
  janitor::clean_names()


litters_df =
   read_csv("Data/FAS_litters.csv", na = c("NA", ".", ""))%>% 
  janitor::clean_names()
separate(group, into = c("dose", "tx_day"), sep = 3)

fas_df =
  left_join(pups_df, litters_df, by = litter_number)

fas_df %>% 
  select(pd_ears:tx_day) %>% 
  pivot_longer(
    pd_ears:pd_walk, 
    names_to = "outcome",
    names_prefix = "pd_",
    values_to = "pn_day" %>% 
      drop_na() %>% 
      ggplot(aes(x = dose, y= pn_day))
    geom_violin() +
      facet_grid(tx_day ~)
  )
  
```

